### ISSUE TITLE
Sample UI5WC + TypeScript + Tests

### ISSUE THREAD

**Issue by lucasheim** [SAP-samples/ui5-webcomponents-sample-react#28]
Do you have any working examples of a TypeScript React App, using UI5 Web Components, with tests using Jest? 

I've tried creating an app with `create-react-app --template typescript`, then adding UI5 WC, but as soon as I started importing the components in my files, I had several problems when running the pre-configured tests.

Example:

App.tsx
```typescript
import React from 'react';
import { Button } from "@ui5/webcomponents-react/lib/Button";
import { Title } from "@ui5/webcomponents-react/lib/Title";

function App() {
  return (
    <div className="App">
      <h1>HTML Hello World</h1>
      <Title>UI5 Hello World</Title>
      <Button>UI5 Button</Button>
    </div>
  );
}

export default App;
```

App.test.tsx
```typescript
import React from 'react';
import { render } from '@testing-library/react';
import App from './App';

test('renders learn react link', () => {
  const { getByText } = render(<App />);
  const linkElement = getByText(/learn react/i);
  expect(linkElement).toBeInTheDocument();
});
```

(I know the assertion would fail, but I couldn't even get to this point)

When running `yarn test`:

![image](https://user-images.githubusercontent.com/13325346/78252050-9fb5e280-74c8-11ea-9b00-f95782fea6fc.png)

**Comment by lucasheim** [comment]
The error is actually the same when running without typescript.

**Comment by fifoosid** [comment]
Hi @lucasheim 

I think that this [issue](https://github.com/SAP/ui5-webcomponents/issues/1176) might be helpful for you. Especially https://github.com/SAP/ui5-webcomponents/issues/1176#issuecomment-597105627

Best regards,
Filip

**Comment by lucasheim** [comment]
Hi @fifoosid. The solution worked. Thanks a lot!
